name: CI/CD StudyTalk

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '17'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Change to back-end directory
      run: cd ./back-end

    - name: Set execute permissions for gradlew
      run: chmod +x gradlew
      
    - name: Run tests
      run: ./gradlew clean test

    - name: Build with Maven
      run: ./gradlew clean build

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v4.0.0
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          mateusnosse/studytalk:latest
          mateusnosse/studytalk:v${{ github.run_number }}
  CD:
    name: Deploy
    needs: [CI]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
